s,@DATADIR@,/home/493914/local/share,g
s,@TERMINFO@,/home/493914/local/share/terminfo,g
s,@TERMINFO_DIRS@,/home/493914/local/share/terminfo,g
s,@NCURSES_MAJOR@,6,g
s,@NCURSES_MINOR@,5,g
s,@NCURSES_PATCH@,20240427,g
s,@NCURSES_OSPEED@,short,g
s,@CAPTOINFO@,captoinfo,g
s,@CLEAR@,clear,g
s,@INFOCMP@,infocmp,g
s,@INFOTOCAP@,infotocap,g
s,@RESET@,reset,g
s,@TABS@,tabs,g
s,@TIC@,tic,g
s,@TOE@,toe,g
s,@TPUT@,tput,g
s,@TSET@,tset,g
